// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9Tb8PpIrrAa2oOe1Wfg1NslBOgV-X8N0',
    appId: '1:704450235245:web:b7420e70436849dced2864',
    messagingSenderId: '704450235245',
    projectId: 'flutter-music-36930',
    authDomain: 'flutter-music-36930.firebaseapp.com',
    storageBucket: 'flutter-music-36930.firebasestorage.app',
    measurementId: 'G-SEJWTQ5CR2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUS7_qa8Uozyuzg6tiNFC5gdYUiICk_UM',
    appId: '1:704450235245:android:c7eaca7ab11db9a6ed2864',
    messagingSenderId: '704450235245',
    projectId: 'flutter-music-36930',
    storageBucket: 'flutter-music-36930.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByXReeIpPH6sZrara6gBMabNTqQ70Vl6A',
    appId: '1:704450235245:ios:7cab6a9889fd1215ed2864',
    messagingSenderId: '704450235245',
    projectId: 'flutter-music-36930',
    storageBucket: 'flutter-music-36930.firebasestorage.app',
    iosBundleId: 'com.romain.flutterspotifyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByXReeIpPH6sZrara6gBMabNTqQ70Vl6A',
    appId: '1:704450235245:ios:f0aa6d9fc8044b1eed2864',
    messagingSenderId: '704450235245',
    projectId: 'flutter-music-36930',
    storageBucket: 'flutter-music-36930.firebasestorage.app',
    iosBundleId: 'com.example.myFirstProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9Tb8PpIrrAa2oOe1Wfg1NslBOgV-X8N0',
    appId: '1:704450235245:web:ae1e956328b4f1bded2864',
    messagingSenderId: '704450235245',
    projectId: 'flutter-music-36930',
    authDomain: 'flutter-music-36930.firebaseapp.com',
    storageBucket: 'flutter-music-36930.firebasestorage.app',
    measurementId: 'G-XMN1XB9L1W',
  );
}
